name: Bug report
description: File a bug report
title: "[Bug] "
labels: bug
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: E.g. "the quality won't change"
    validation:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      placeholder: E.g. go to a /watch page and then click on another video
  - type: textarea
    id: expected-behavior
    validation:
      required: true
    attributes:
      label: Expected bahavior
      placeholder: E.g. the quality should change to 1080p at 60FPS but is instead 720p
  - type: dropdown
    id: browsers
    attributes: What browser(s) can you reproduce the issue on?
    multiple: true
    options:
    - Chorme
    - Firefox
    - Chromium Edge
    - Opera
    - Vivaldi
    - Brave
    - Safari
  - type: dropdown
    id: operating-system
    attributes: What OS does it occur on?
    options:
    - Windows
    - macOS
    - Linux
    - Android
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
  - type: input
    id: version
    attributes:
      label: What's the version you're running?
      description: Go to the extensions page and copy the version number
      validation:
        required: true
